# -*- coding: utf-8 -*-
"""populationGrowth_Simulation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D7-4CSYcAX94UIpoCXS5QKlb2HjdZjld
"""

import random

'''
totalPopulation = 50
growthFactor = 1.00005
dayCount = 0

while totalPopulation < 10000:
  totalPopulation *= growthFactor

  dayCount+=1
  if dayCount == 56:
    dayCount = 0
    print(totalPopulation)
'''

startingPopulation = 18
infantMortality = 5
agriculture = 5
disasterChance = 10
food = 0
fertilityx = 18
fertilityy = 35

peopleDictionary = []
class Person:
  def __init__(self, age):
    self.gender = random.randint(0,1)
    self.age = age

def harvest(food, agriculture):
  ablePeople = 0
  for person in peopleDictionary:
    if person.age > 8:
      ablePeople+=1

  food += ablePeople*agriculture

  if food<len(peopleDictionary):
    del peopleDictionary[0:int(len(peopleDictionary)-food)]
    food = 0
  else:
    food-=len(peopleDictionary)

def reproduce(fertilityx, fertilityy,infantMortality):
  for person in peopleDictionary:
    if person.gender == 1:
      if person.age > fertilityx and person.age < fertilityy:
        if random.randint(0,5) == 1:
          if random.randint(0,100)>infantMortality:
            peopleDictionary.append(Person(0))

def beginSim():
  for x in range(startingPopulation):
    peopleDictionary.append(Person(random.randint(18,50)))

beginSim()

#peopleDictionary
def runYear(food, agriculture, fertilityx, fertilityy, infantMortality, disasterChance):
  harvest(food, agriculture)
  reproduce(fertilityx,fertilityy, infantMortality)
  for person in peopleDictionary:
    if person.age > 80:
      peopleDictionary.remove(person)
    else:
      person.age +=1

    if random.randint(0,100)<disasterChance:
      del peopleDictionary[0:int(random.uniform(0.05,0.2)*len(peopleDictionary))]

    print(len(peopleDictionary))
    infantMortality *=0.985
    return infantMortality

while len(peopleDictionary)<100 and len(peopleDictionary)>1:
  infantMortality = runYear(food, agriculture, fertilityx, fertilityy, infantMortality, disasterChance)